academicstoday_project/academicstoday_project/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static, settings

urlpatterns = [
    # Examples:
    # url(r'^$', 'academicstoday_project.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
               
    # This regex makes the default URL for the website to launch this view.
    url(r'', include('landpage.urls')),
    url(r'', include('registration.urls')),
    url(r'', include('login.urls')),
    url(r'', include('account.urls')),
    url(r'', include('registrar.urls')),
    url(r'', include('student.urls')),
    url(r'', include('teacher.urls')),
    url(r'', include('publisher.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

academicstoday_project/login/urls.py
from django.conf.urls import patterns, include, url
from . import views

urlpatterns = patterns('',
    url(r'^login_modal$', views.login_modal),
    url(r'^login$', views.login_authentication),
    url(r'^logout$', views.logout_authentication),

)

academicstoday_project/registrar/urls.py
from django.conf.urls import patterns, include, url

from registrar.views import courses
from registrar.views import enrollment
from registrar.views import teaching
from registrar.views import transcript
from registrar.views import certificate

urlpatterns = patterns('',
    # Courses
    url(r'^courses$', courses.courses_page),
    url(r'^enroll$', courses.enroll),

    # Enrollment(s)
    url(r'^enrollment$', enrollment.enrollment_page),
    url(r'^enrollment_table$', enrollment.enrollment_table),
    url(r'^disenroll_modal$', enrollment.disenroll_modal),
    url(r'^disenroll', enrollment.disenroll),
         
    # Teaching
    url(r'^teaching$', teaching.teaching_page),
    url(r'^refresh_teaching_table$', teaching.refresh_teaching_table),
                       
    url(r'^course_modal$', teaching.course_modal),
    url(r'^save_course$', teaching.save_course),
    url(r'^delete_course_modal$', teaching.delete_course_modal),
    url(r'^course_delete$', teaching.course_delete),
                    
    # Transcript
    url(r'^transcript$', transcript.transcript_page),
                       
    # Certificate(s)
    url(r'^certificates$', certificate.certificates_page),
    url(r'^certificates_table$', certificate.certificates_table),
    url(r'^change_certificate_accessiblity$', certificate.change_certificate_accessiblity),
    url(r'^certificate/(\d+)$', certificate.certificate_page),
    url(r'^certificate_permalink_modal$', certificate.certificate_permalink_modal),
)

academicstoday_project/registrar/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings
from django.core.validators import MinValueValidator, MaxValueValidator
import os
from account.models import Student
from account.models import Teacher

WORTH_PERCENT_CHOICES = (
    (0, '0 %'),
    (10, '10 %'),
    (15, '15 %'),
    (20, '20 %'),
    (25, '25 %'),
    (30, '30 %'),
    (35, '35 %'),
    (40, '40 %'),
    (45, '45 %'),
    (50, '50 %'),
    (55, '55 %'),
    (60, '60 %'),
    (65, '65 %'),
    (70, '70 %'),
    (75, '75 %'),
    (80, '80 %'),
    (85, '85 %'),
    (90, '90 %'),
    (95, '95 %'),
    (100, '100 %'),
)

COURSE_CATEGORY_TYPES = (
    ('Aeronautics & Astronautics', 'Aeronautics & Astronautics'),
    ('Anesthesia', 'Anesthesia'),
    ('Anthropology', 'Anthropology'),
    ('Applied Physics', 'Applied Physics'),
    ('Art or Art History', 'Art & Art History'),
    ('Astrophysics', 'Astrophysics'),
    ('Biochemistry', 'Biochemistry'),
    ('Bioengineering', 'Bioengineering'),
    ('Biology', 'Biology'),
    ('Business', 'Business'),
    ('Cardiothoracic Surgery', 'Cardiothoracic Surgery'),
    ('Chemical and Systems Biology', 'Chemical and Systems Biology'),
    ('Chemical Engineering', 'Chemical Engineering'),
    ('Chemistry', 'Chemistry'),
    ('Civil and Environmental Engineering', 'Civil and Environmental Engineering'),
    ('Classics', 'Classics'),
    ('Communication', 'Communication'),
    ('Comparative Literature', 'Comparative Literature'),
    ('Comparative Medicine', 'Comparative Medicine'),
    ('Computer Science', 'Computer Science'),
    ('Dermatology', 'Dermatology'),
    ('Developmental Biology', 'Developmental Biology'),
    ('East Asian Languages and Cultures', 'East Asian Languages and Cultures'),
    ('Economics', 'Economics'),
    ('Education', 'Education'),
    ('Electrical Engineering', 'Electrical Engineering'),
    ('English', 'English'),
    ('French', 'French'),
    ('Genetics', 'Genetics'),
    ('General Eduction', 'General Education'),
    ('Geological and Environmental Sciences', 'Geological and Environmental Sciences'),
    ('Geophysics', 'Geophysics'),
    ('Health', 'Health'),
    ('History', 'History'),
    ('Latin American Cultures', 'Latin American Cultures'),
    ('Law School', 'Law School'),
    ('Linguistics', 'Linguistics'),
    ('Management', 'Management'),
    ('Materials Science', 'Materials Science'),
    ('Mathematics', 'Mathematics'),
    ('Mechanical Engineering', 'Mechanical Engineering'),
    ('Medicine', 'Medicine'),
    ('Microbiology and Immunology', 'Microbiology and Immunology'),
    ('Molecular and Cellular Physiology', 'Molecular and Cellular Physiology'),
    ('Music', 'Music'),
    ('Neurobiology', 'Neurobiology'),
    ('Neurology', 'Neurology'),
    ('Neurosurgery', 'Neurosurgery'),
    ('Obstetrics and Gynecology', 'Obstetrics and Gynecology'),
    ('Ophthalmology', 'Ophthalmology'),
    ('Orthopaedic Surgery', 'Orthopaedic Surgery'),
    ('Other', 'Other'),
    ('Otolaryngology', 'Otolaryngology'),
    ('Pathology', 'Pathology'),
    ('Pediatrics', 'Pediatrics'),
    ('Philosophy', 'Philosophy'),
    ('Physics', 'Physics'),
    ('Political Science', 'Political Science'),
    ('Psychiatry', 'Psychiatry'),
    ('Psychology', 'Psychology'),
    ('Radiation Oncology', 'Radiation Oncology'),
    ('Radiology', 'Radiology'),
    ('Religious Studies', 'Religious Studies'),
    ('Slavic Languages and Literature', 'Slavic Languages and Literature'),
    ('Sociology', 'Sociology'),
    ('Statistics', 'Statistics'),
    ('Surgery', 'Surgery'),
    ('Theater and Performance Studies', 'Theater and Performance Studies'),
    ('Urology', 'Urology'),
)


class FileUpload(models.Model):
    upload_id = models.AutoField(primary_key=True)
    type = models.PositiveSmallIntegerField(default=settings.UNKNOWN_FILE_UPLOAD_TYPE)
    title = models.CharField(max_length=127, null=True)
    description = models.TextField(null=True)
    upload_date = models.DateField(auto_now= True, null=True)
    file = models.FileField(upload_to='uploads', null=True)
    user = models.ForeignKey(User)
    
    def delete(self, *args, **kwargs):
        """
            Overrided delete functionality to include deleting the local file
            that we have stored on the system. Currently the deletion funciton
            is missing this functionality as it's our responsibility to handle
            the local files.
        """
        if self.file:
            if os.path.isfile(self.file.path):
                os.remove(self.file.path)
        super(FileUpload, self).delete(*args, **kwargs) # Call the "real" delete() method
    
    def __str__(self):
        return self.title
    
    class Meta:
        db_table = 'at_file_uploads'


class Course(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=127)
    sub_title = models.CharField(max_length=127)
    category = models.CharField(max_length=127, choices=COURSE_CATEGORY_TYPES, default='General Education')
    description = models.TextField(null=True)
    start_date = models.DateField(null=True)
    finish_date = models.DateField(null=True)
    is_official = models.BooleanField(default=False)
    status = models.PositiveSmallIntegerField(default=settings.COURSE_UNAVAILABLE_STATUS)
    image = models.ImageField(upload_to='uploads', null=True, blank=True)
    students = models.ManyToManyField(Student)
    teacher = models.ForeignKey(Teacher)

    def delete(self, *args, **kwargs):
        if self.image:
            if os.path.isfile(self.image.path):
                os.remove(self.image.path)
        super(Course, self).delete(*args, **kwargs) # Call the "real" delete() method

    def __str__(self):
        return self.title

    class Meta:
        db_table = 'at_courses'


class CourseSubmission(models.Model):
    review_id = models.AutoField(primary_key=True)
    status = models.PositiveSmallIntegerField(default=settings.COURSE_SUBMITTED_FOR_REVIEW_STATUS)
    from_submitter = models.TextField(null=True)
    from_reviewer = models.TextField(null=True)
    review_date = models.DateField(auto_now=True, null=True)
    submission_date = models.DateField(auto_now=True, null=True)
    course = models.ForeignKey(Course)

    def __str__(self):
        return str(self.review_date) + ' ' + str(self.course)

    class Meta:
        db_table = 'at_course_submissions'


class CourseSetting(models.Model):
    settings_id = models.AutoField(primary_key=True)
    course = models.ForeignKey(Course)
    final_exam_percent = models.FloatField(
        validators=[MinValueValidator(0), MaxValueValidator(100)],
        default=50
    )
    course_percent = models.FloatField(
        validators=[MinValueValidator(0), MaxValueValidator(100)],
        default=50
    )
    
    def __str__(self):
        return str(self.settings_id);
    
    class Meta:
        db_table = 'at_course_settings'


class CourseFinalMark(models.Model):
    credit_id = models.AutoField(primary_key=True)
    percent = models.FloatField(
        validators=[MinValueValidator(0), MaxValueValidator(100)],
        default=0
    )
    is_public = models.BooleanField(default=False)
    course = models.ForeignKey(Course)
    student = models.ForeignKey(Student)
        
    def __str__(self):
        return str(self.student) + " " + str(self.course) + " " + str(self.percent) + "%"
                                
    class Meta:
        db_table = 'at_course_final_marks'


class Announcement(models.Model):
    announcement_id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=31)
    body = models.TextField()
    post_date = models.DateField(auto_now_add=True, null=True)
    course = models.ForeignKey(Course)
    
    @classmethod
    def create(cls, course_id, title, body, post_date):
        announcement = cls(course_id=course_id, title=title,
                           body=body, post_date=post_date)
        return announcement

    def __str__(self):
        return str(self.announcement_id) + ' ' + self.title + ' ' + self.body + ' ' + str(self.post_date);

    class Meta:
        db_table = 'at_announcements'


class Syllabus(models.Model):
    syllabus_id = models.AutoField(primary_key=True)
    file = models.FileField(upload_to='uploads',null=True)
    course = models.ForeignKey(Course)

    def delete(self, *args, **kwargs):
        if self.file:
            if os.path.isfile(self.file.path):
                 os.remove(self.file.path)
        super(Syllabus, self).delete(*args, **kwargs) # Call the "real" delete() method

    def __str__(self):
        return str(self.syllabus_id) + ' ' + self.file.url;

    class Meta:
        db_table = 'at_syllabus'


class Policy(models.Model):
    policy_id = models.AutoField(primary_key=True)
    file = models.FileField(upload_to='uploads',null=True)
    course = models.ForeignKey(Course)

    def delete(self, *args, **kwargs):
        if self.file:
            if os.path.isfile(self.file.path):
                os.remove(self.file.path)
        super(Policy, self).delete(*args, **kwargs) # Call the "real" delete() method

    def __str__(self):
        return str(self.policy_id) + ' ' + self.file.url;

    class Meta:
        db_table = 'at_policys'


class Lecture(models.Model):
    lecture_id = models.AutoField(primary_key=True)
    lecture_num = models.PositiveSmallIntegerField(
        validators=[MinValueValidator(1)],
        default=1
    )
    week_num = models.PositiveSmallIntegerField(
        validators=[MinValueValidator(1)],
        default=1
    )
    title = models.CharField(max_length=63, default='', null=True)
    description = models.TextField(default='', null=True)
    youtube_url = models.URLField(null=True, blank=True)
    vimeo_url = models.URLField(null=True, blank=True)
    bliptv_url = models.URLField(null=True, blank=True)
    VIDEO_PLAYER_CHOICES = (
        (settings.YOUTUBE_VIDEO_PLAYER, 'YouTube'),

academicstoday_project/registrar/views/certificate.py
from django.shortcuts import render
from django.core import serializers
import json
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.conf import settings
from landpage.models import CoursePreview
from registrar.models import Student
from registrar.models import Teacher
from registrar.models import Course
from registrar.models import CourseFinalMark
from registrar.models import CourseSetting


from registrar.forms import CourseForm


@login_required(login_url='/landpage')
def certificates_page(request):
    # Create our student account which will build our registration around.
    try:
        student = Student.objects.get(user=request.user)
    except Student.DoesNotExist:
        student = Student.objects.create(user=request.user)
    try:
        marks = CourseFinalMark.objects.filter(student=student)
    except CourseFinalMark.DoesNotExist:
        marks = None

    return render(request, 'registrar/certificate/view.html',{
        'student': student,
        'marks': marks,
        'user': request.user,
        'tab': 'certificates',
        'HAS_ADVERTISMENT': settings.APPLICATION_HAS_ADVERTISMENT,
        'local_css_urls': settings.SB_ADMIN_2_CSS_LIBRARY_URLS,
        'local_js_urls': settings.SB_ADMIN_2_JS_LIBRARY_URLS
    })


@login_required()
def certificates_table(request):
    # Create our student account which will build our registration around.
    try:
        student = Student.objects.get(user=request.user)
    except Student.DoesNotExist:
        student = Student.objects.create(user=request.user)
    try:
        marks = CourseFinalMark.objects.filter(student=student)
    except CourseFinalMark.DoesNotExist:
        marks = None

    return render(request, 'registrar/certificate/table.html',{
        'student': student,
        'marks': marks,
        'user': request.user,
    })


@login_required(login_url='/landpage')
def change_certificate_accessiblity(request):
    response_data = {'status' : 'failed', 'message' : 'unknown error with saving'}
    if request.is_ajax():
        if request.method == 'POST':
            credit_id = int(request.POST['credit_id'])
            try:
                mark = CourseFinalMark.objects.get(credit_id=credit_id)
                if mark.is_public:
                    mark.is_public = False
                else:
                    mark.is_public = True
                mark.save()
                response_data = {'status' : 'success', 'message' : 'certificate accessiblity changed'}
            except CourseFinalMark.DoesNotExist:
                response_data = {'status' : 'failure', 'message' : 'certificate does not exist'}
    return HttpResponse(json.dumps(response_data), content_type="application/json")


@login_required()
def certificate_page(request, credit_id):
    # Create our student account which will build our registration around.
    try:
        student = Student.objects.get(user=request.user)
    except Student.DoesNotExist:
        student = Student.objects.create(user=request.user)
    try:
        mark = CourseFinalMark.objects.get(credit_id=credit_id)
    except CourseFinalMark.DoesNotExist:
        mark = None

    return render(request, 'registrar/certificate/certificate.html',{
        'student': student,
        'mark': mark,
        'user': request.user,
        'tab': 'certificates',
        'HAS_ADVERTISMENT': settings.APPLICATION_HAS_ADVERTISMENT,
        'local_css_urls': settings.SB_ADMIN_2_CSS_LIBRARY_URLS,
        'local_js_urls': settings.SB_ADMIN_2_JS_LIBRARY_URLS
    })


@login_required()
def certificate_permalink_modal(request):
    credit_id = int(request.POST['credit_id'])
    try:
        mark = CourseFinalMark.objects.get(credit_id=credit_id)
    except CourseFinalMark.DoesNotExist:
        mark = None
    return render(request, 'registrar/certificate/permalink_modal.html',{
        'mark': mark,
        'user': request.user,
        'tab': 'certificates',
        'local_css_urls': settings.SB_ADMIN_2_CSS_LIBRARY_URLS,
        'local_js_urls': settings.SB_ADMIN_2_JS_LIBRARY_URLS
    })

academicstoday_project/registrar/templates/registrar/teaching/course_form.html
<form enctype="multipart/form-data" name="course_form" id="course_form">
    <input type="hidden"
            id="id_id"
          name="id"
         value={% if form.instance.id != None %}"{{ form.instance.id }}"{% else %}0{% endif %}>
    {% for field in form %}
    <div class="row">
        <div class="form-group">
            <div class="fieldWrapper">
                <label class="col-sm-3 control-label">
                    {{ field.label }}
                </label>
                <div class="col-sm-9">
                    {{ field }}
                </div>
            </div>
        </div>
    </div>
    <br/>
    {% endfor %}
</form>

academicstoday_project/registrar/templates/registrar/teaching/delete_course_modal.html
<div class="modal fade" id="delete_course_modal" role="dialog">
    <div class="modal-dialog" style="width:50%;">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <h2 class="modal-title" id="myModalLabel">Warning</h2>
            </div>
            <div class="modal-body">
                <div class="well">
                    <p>When you delete a course, all data associated with this course will get deleted, this includes Student credits! Suspending is preferred option if the course was a successfully completed. Furthermore, all deletions are permanent, your course cannot be retrieved once deleted.</p>
                </div>
            </div>
            <div class="modal-footer">
                <button onclick="$('#delete_course_modal').modal('hide');"
                           type="button"
                          class="btn-lg btn-default">
                    <i class="fa fa-circle-o"></i> Cancel
                </button>
                <button type="button"
                       class="btn-lg btn-danger"
                     onclick="ajax_delete_course({{ course.id }});">
                    <i class="fa fa-check-circle"></i> Yes I Understand, Delete this Course
                </button>
            </div>
        </div>
    </div>
</div>
<script>
    /**
     * Dynamic UI Code.
     *  To give our application a dynamic feel, the following jQuery code will be
     *  used to perform various UI changes.
     */
     $(document).ready(function(){
        $('#delete_course_modal').on('hidden.bs.modal', function (e) {
            $('#ajax_modal_placeholder').html('');
            $('#del_{{ course.id }}_btn').prop("disabled", false); // Unlock button
        });
    });
    
    /**
     *  Function will call AJAX function to delete the teacher's course.
     */
    function ajax_delete_course(course_id)
    {
        $('#del_' + course_id + '_btn').prop("disabled", true); // Lock button
        $.ajax( 'course_delete', {
            data: {
               'csrfmiddlewaretoken': '{{ csrf_token }}',
               'course_id' : course_id
            },
            type: 'post',
            success: function(result) {
               // success code execution here
               if (result.status == 'success')
               {
                    $('#delete_course_modal').modal('hide');
                    ajax_refresh_teaching_table();
               }
            },
            error: function(xhr,status,error) {
               // error code here
            },
            complete: function(xhr,status) {
               // completion code here
               $('#del_' + course_id + '_btn').prop("disabled", false); // Unlock button
            }
        });
    }
</script>

academicstoday_project/registrar/templates/registrar/teaching/new_course_modal.html
<div class="modal fade" id="new_course_modal" role="dialog">
    <div class="modal-dialog" style="width:50%;">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <h2 class="modal-title" id="myModalLabel">New Course</h2>
            </div>
            <div class="modal-body">
                {% include "registrar/teaching/course_form.html" with form=course_form %}
                
                <!-- Error Message Box -->
                <div id="error_box" name="error_box" class="alert alert-danger alert-dismissable" hidden="true">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    ERROR: This is to be filled in by the "print_error" function. If you see this message that means there's an error with your javascript somewhere.
                </div><!-- /.Error Message Box -->
            </div>
            <div class="modal-footer">
                <button onclick="ajax_create_course();"
                             id="submit_btn"
                           name="submit_btn"
                           type="button"
                          class="btn btn-primary">
                    <i class="fa fa-check-circle"></i> Submit
                </button>
            </div>
        </div>
    </div>
</div>
<script>
    /**
     * Dynamic UI Code.
     *  To give our application a dynamic feel, the following jQuery code will be
     *  used to perform various UI changes.
     */
     $(document).ready(function(){
        $('#new_course_modal').on('hidden.bs.modal', function (e) {
            $('#ajax_modal_placeholder').html('');
            $('#new_course_btn').prop("disabled", false); // Unlock button
            $('#edit_{{ course.id }}_btn').prop("disabled", false); // Unlock button   
        });
    });
    
    /**
     *  Function will call AJAX function to load the register.
     */
    function ajax_create_course()
    {
        $('#submit_btn').prop("disabled", true);
        
        // create a FormData Object using your form dom element
        var data = new FormData();
        data.append('csrfmiddlewaretoken', '{{ csrf_token }}');
        data.append('course_id', $('#id_id').val());
        data.append('title', $('#id_title').val());
        data.append('sub_title', $('#id_sub_title').val());
        data.append('category', $('#id_category').val());
        data.append('description', $('#id_description').val());
        data.append('image', document.getElementById('id_image').files[0]);
        var date = '';
        date  = $('#id_start_date_year').val() + '-';
        date += $('#id_start_date_month').val() + '-';
        date += $('#id_start_date_day').val();
        data.append('start_date', date);
        date  = $('#id_finish_date_year').val() + '-';
        date += $('#id_finish_date_month').val() + '-';
        date += $('#id_finish_date_day').val();
        data.append('finish_date', date);

        jQuery.ajax({
            url: 'save_course',
            data: data,
            cache: false,
            contentType: false,
            processData: false,
            type: 'POST',
            success: function(json_result){
                // success code execution here
                if (json_result.status == "success")
                {
                    $('#new_course_modal').modal('hide');
                    ajax_refresh_teaching_table();
                }
                else
                {
                    print_error(json_result.message);
                }
            },
            error: function(xhr,status,error) {
                // error code here
            },
            complete: function(xhr,status) {
               // completion code here
               $('#submit_btn').prop("disabled", false);
            }
        });

    }

    /**
     * Prints a error box with the contents of the errors received from the server.
     */
    function print_error(json_result)
    {
        $('#error_box').prop("hidden", false); // Display error box.
    
        // Iterate through the JSON array of arrays and generate an error string.
        var message = "<b>Error(s):</b><hr/>";
        var data = $.parseJSON(json_result)
        for (var key in data) {
            if (data.hasOwnProperty(key)) { // this will check if key is owned by data object and not by any of it's ancestors
                message += "<p>" + key + ": " + data[key] + "<p>";
             }
         }
    
        // Replace the error string with the contents of the error box.
        $('#error_box').html(message);
    }
</script>

academicstoday_project/registrar/templates/registrar/teaching/table.html
        <!-- Course Rows -->
        <div class="row">
            <div class="col-lg-12 text-center">
                <div class="panel panel-default">
                    <div class="panel-body">
                      <div class="table-responsive">
                          <table class="table table-hover table-striped">
                              <thead>
                                  <tr>
                                      <th>Title</th>
                                      <th>
                                          <button onclick="ajax_course_modal(0);"
                                                       id="new_course_btn"
                                                     name="new_course_btn"
                                                     type="button"
                                                    class="btn btn-lg btn-success">
                                              <i class="fa fa-plus"></i> Add
                                          </button>
                                      </th>
                                  </tr>
                              </thead>
                              <tbody>
                              {% for course in courses.all %}
                                  <tr>
                                      <td align="left" valign="left">{{ course.title }}</td>
                                      <td align="left" valign="left">
                                         <button onclick="ajax_course_modal({{ course.id }});"
                                                       id="edit_{{ course.id }}_btn"
                                                     name="edit_{{ course.id }}_btn"
                                                    type="button"
                                                   class="btn btn-lg btn-warning">
                                            <i class="fa fa-pencil"></i> Edit
                                        </button>
                                        <button onclick="view_course_page({{ course.id }});"
                                                   type="button"
                                                  class="btn btn-lg btn-primary">
                                            <i class="fa fa-level-down"></i> View
                                        </button>
                                        <button onclick="ajax_delete_course_modal({{ course.id }});"
                                                     id="del_{{ course.id }}_btn"
                                                   name="del_{{ course.id }}_btn"
                                                   type="button"
                                                  class="btn btn-lg btn-danger">
                                            <i class="fa fa-minus"></i> Delete
                                        </button>
                                      </td>
                                  </tr>
                            {% endfor %}
                            </tbody>
                          </table>
                      </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- /.Course Rows -->