academicstoday_project/academicstoday_project/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static, settings

urlpatterns = [
    # Examples:
    # url(r'^$', 'academicstoday_project.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
               
    # This regex makes the default URL for the website to launch this view.
    url(r'', include('landpage.urls')),
    url(r'', include('registration.urls')),
    url(r'', include('login.urls')),
    url(r'', include('account.urls')),
    url(r'', include('registrar.urls')),
    url(r'', include('student.urls')),
    url(r'', include('teacher.urls')),
    url(r'', include('publisher.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

academicstoday_project/login/urls.py
from django.conf.urls import patterns, include, url
from . import views

urlpatterns = patterns('',
    url(r'^login_modal$', views.login_modal),
    url(r'^login$', views.login_authentication),
    url(r'^logout$', views.logout_authentication),

)

academicstoday_project/student/urls.py
from django.conf.urls import patterns, include, url

from . import views

# Import custom views.
from student.views import announcement
from student.views import syllabus
from student.views import policy
from student.views import lecture
from student.views import lecture_note
from student.views import assignment
from student.views import quiz
from student.views import exam
from student.views import discussion
from student.views import peer_review
from student.views import credit

urlpatterns = patterns('',
    # Announcement
    url(r'^course/(\d+)/announcements$', announcement.announcements_page),

    # Syllabus
    url(r'^course/(\d+)/syllabus$', syllabus.syllabus_page),

    # Grades & Policy
    url(r'^course/(\d+)/policy$', policy.policy_page),

    # Lecture
    url(r'^course/(\d+)/lectures$', lecture.lectures_page),
    url(r'^course/(\d+)/lecture$', lecture.lecture),
                       
    # Lecture Notes
    url(r'^course/(\d+)/lecture/(\d+)/notes$', lecture_note.lecture_notes_page),
    url(r'^course/(\d+)/lecture/(\d+)/view_lecture_note$', lecture_note.view_lecture_note),

    # Assignment(s)
    url(r'^course/(\d+)/assignments$', assignment.assignments_page),
    url(r'^course/(\d+)/assignments_table$', assignment.assignments_table),
    url(r'^course/(\d+)/delete_assignment$', assignment.delete_assignment),
                       
    # Assignment
    url(r'^course/(\d+)/assignment/(\d+)$', assignment.assignment_page),
    url(r'^course/(\d+)/assignment/(\d+)/submit_assignment$', assignment.submit_assignment),
    url(r'^course/(\d+)/assignment/(\d+)/submit_e_assignment_answer$', assignment.submit_e_assignment_answer),
    url(r'^course/(\d+)/assignment/(\d+)/submit_mc_assignment_answer$', assignment.submit_mc_assignment_answer),
    url(r'^course/(\d+)/assignment/(\d+)/submit_tf_assignment_answer$', assignment.submit_tf_assignment_answer),
    url(r'^course/(\d+)/assignment/(\d+)/submit_r_assignment_answer$', assignment.submit_r_assignment_answer),
                       
    # Quiz(zes)
    url(r'^course/(\d+)/quizzes$', quiz.quizzes_page),
    url(r'^course/(\d+)/quizzes_table$', quiz.quizzes_table),
    url(r'^course/(\d+)/quiz_delete$', quiz.delete_quiz),
                       
    # Quiz
    url(r'^course/(\d+)/quiz/(\d+)$', quiz.quiz_page),
    url(r'^course/(\d+)/quiz/(\d+)/submit_quiz$', quiz.submit_quiz),
    url(r'^course/(\d+)/quiz/(\d+)/submit_tf_quiz_answer$', quiz.submit_tf_assignment_answer),

    # Exam(s)
    url(r'^course/(\d+)/exams$', exam.exams_page),
    url(r'^course/(\d+)/exams_table$', exam.exams_table),
    url(r'^course/(\d+)/delete_exam$', exam.delete_exam),
                       
    # Exam
    url(r'^course/(\d+)/exam/(\d+)$', exam.exam_page),
    url(r'^course/(\d+)/exam/(\d+)/submit_exam$', exam.submit_exam),
    url(r'^course/(\d+)/exam/(\d+)/submit_mc_exam_answer$', exam.submit_mc_exam_answer),

    # Peer-Review
    url(r'^course/(\d+)/peer_reviews$', peer_review.peer_reviews_page),
    url(r'^course/(\d+)/peer_review/(\d+)$', peer_review.assignment_page),
    url(r'^course/(\d+)/peer_review/(\d+)/peer_review_modal$', peer_review.peer_review_modal),
    url(r'^course/(\d+)/peer_review/(\d+)/save_peer_review$', peer_review.save_peer_review),
    url(r'^course/(\d+)/peer_review/(\d+)/delete_peer_review$', peer_review.delete_peer_review),
    url(r'^course/(\d+)/peer_review/(\d+)/update_assignment_marks$', peer_review.update_assignment_marks),
                       
    # Discussion
    url(r'^course/(\d+)/discussion$', discussion.discussion_page),
    url(r'^course/(\d+)/threads_table$', discussion.threads_table),
    url(r'^course/(\d+)/new_thread$', discussion.new_thread_modal),
    url(r'^course/(\d+)/insert_thread$', discussion.insert_thread),
    url(r'^course/(\d+)/delete_thread$', discussion.delete_thread),                   
    url(r'^course/(\d+)/thread/(\d+)$', discussion.thread_page),
    url(r'^course/(\d+)/thread/(\d+)/posts_table$', discussion.posts_table),
    url(r'^course/(\d+)/thread/(\d+)/new_post$', discussion.new_post_modal),
    url(r'^course/(\d+)/thread/(\d+)/insert_post$', discussion.insert_post),
                       
    # Credit
    url(r'^course/(\d+)/credit$', credit.credit_page),
    url(r'^course/(\d+)/submit_credit_application$', credit.submit_credit_application),
)

academicstoday_project/account/models.py
from django.db import models
from django.contrib.auth.models import User


class PrivateMessage(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=127)
    text = models.TextField()
    sent_date = models.DateField(auto_now_add=True, null=True)
    to_address = models.CharField(max_length=255)
    from_address = models.CharField(max_length=255)
    
    def __str__(self):
        return "From: " + self.from_address + " To: " + self.to_address + " Title: " + self.title
    
    class Meta:
        db_table = 'at_private_messages'


class Student(models.Model):
    student_id = models.AutoField(primary_key=True)
    user = models.ForeignKey(User)
    
    def __str__(self):
        return self.user.first_name + " " + \
                          self.user.last_name 
    
    class Meta:
        db_table = 'at_students'


class Teacher(models.Model):
    teacher_id = models.AutoField(primary_key=True)
    user = models.ForeignKey(User)
    
    def __str__(self):
        return self.user.first_name + " " + \
            self.user.last_name + " "
    
    class Meta:
        db_table = 'at_teachers'

academicstoday_project/registrar/views/courses.py
from django.shortcuts import render
from django.core import serializers
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.conf import settings
import json
from landpage.models import CoursePreview
from registrar.models import Student
from registrar.models import Teacher
from registrar.models import Course
from registrar.models import CourseFinalMark
from registrar.models import CourseSetting
from registrar.forms import CourseForm


@login_required(login_url='/landpage')
def courses_page(request):
    course_list = Course.objects.filter(status=settings.COURSE_AVAILABLE_STATUS)
    paginator = Paginator(course_list, 25) # Show 25 courses per page
    page = request.GET.get('page')
    try:
        courses = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        courses = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        courses = paginator.page(paginator.num_pages)

    # Create our student account which will build our registration around.
    try:
         student = Student.objects.get(user=request.user)
    except Student.DoesNotExist:
         student = Student.objects.create(user=request.user)

    # Only fetch teacher and do not create new teacher here.
    try:
        teacher = Teacher.objects.get(user=request.user)
    except Teacher.DoesNotExist:
        teacher = None

    return render(request, 'registrar/courses/list.html',{
        'courses' : courses,
        'student' : student,
        'teacher' : teacher,
        'user' : request.user,
        'tab' : 'courses',
        'HAS_ADVERTISMENT': settings.APPLICATION_HAS_ADVERTISMENT,
        'local_css_urls' : settings.SB_ADMIN_2_CSS_LIBRARY_URLS,
        'local_js_urls' : settings.SB_ADMIN_2_JS_LIBRARY_URLS
    })


@login_required()
def enroll(request):
    response_data = {'status' : 'failure', 'message' : 'unsupported request format'}
    if request.is_ajax():
        course_id = int(request.POST['course_id'])
        student = Student.objects.get(user=request.user)
        course = Course.objects.get(id=course_id)

        # Lookup the course in the students enrollment history and if the
        # student is not enrolled, then enroll them now.
        try:
            Course.objects.get(
                students__student_id=student.student_id,
                id=course_id
            )
        except Course.DoesNotExist:
            course.students.add(student)
        response_data = {'status' : 'success', 'message' : 'enrolled' }

    return HttpResponse(json.dumps(response_data), content_type="application/json")

# Developer Notes: Pagination
# https://docs.djangoproject.com/en/1.8/topics/pagination/

academicstoday_project/student/views/announcement.py
from django.shortcuts import render
from django.core import serializers
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.conf import settings
import json
import datetime
from registrar.models import Student
from registrar.models import Course
from registrar.models import Announcement


@login_required(login_url='/landpage')
def announcements_page(request, course_id):
    course = Course.objects.get(id=course_id)
    try:
        announcements = Announcement.objects.filter(course=course).order_by('-post_date')
    except Announcement.DoesNotExist:
        announcements = None
    return render(request, 'course/announcement/view.html',{
        'course' : course,
        'announcements' : announcements,
        'user' : request.user,
        'tab' : 'announcements',
        'HAS_ADVERTISMENT': settings.APPLICATION_HAS_ADVERTISMENT,
        'local_css_urls' : settings.SB_ADMIN_2_CSS_LIBRARY_URLS,
        'local_js_urls' : settings.SB_ADMIN_2_JS_LIBRARY_URLS,
    })

academicstoday_project/student/views/credit.py
from django.shortcuts import render
from django.core import serializers
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.conf import settings
import json
import datetime
from registrar.models import Course
from registrar.models import CourseFinalMark
from registrar.models import Student
from registrar.models import AssignmentSubmission
from registrar.models import QuizSubmission
from registrar.models import ExamSubmission

@login_required(login_url='/landpage')
def credit_page(request, course_id):
    course = Course.objects.get(id=course_id)
    student = Student.objects.get(user=request.user)
    try:
        final_mark = CourseFinalMark.objects.get(
            course=course,
            student=student,
        )
    except CourseFinalMark.DoesNotExist:
        final_mark = None
    
    return render(request, 'course/credit/list.html',{
        'course' : course,
        'final_mark': final_mark,
        'user' : request.user,
        'tab' : 'credit',
        'HAS_ADVERTISMENT': settings.APPLICATION_HAS_ADVERTISMENT,
        'local_css_urls' : settings.SB_ADMIN_2_CSS_LIBRARY_URLS,
        'local_js_urls' : settings.SB_ADMIN_2_JS_LIBRARY_URLS,
    })


# Function will verify that all criteria to pass the course are met and
# make a record of user completing this course. If user does not meet
# criteria an error will be returned.
@login_required()
def submit_credit_application(request, course_id):
    if request.is_ajax():
        if request.method == 'POST':
            # Fetch from database
            course = Course.objects.get(id=course_id)
            student = Student.objects.get(user=request.user)
            try:
                a_submissions = AssignmentSubmission.objects.filter(
                    assignment__course=course,
                    student=student,
                )
            except AssignmentSubmission.DoesNotExist:
                a_submissions = None
            
            try:
                q_submissions = QuizSubmission.objects.filter(
                    quiz__course=course,
                    student=student,
                )
            except QuizSubmission.DoesNotExist:
                q_submissions = None
            
            try:
                e_submissions = ExamSubmission.objects.filter(
                    exam__course=course,
                    student=student,
                )
            except ExamSubmission.DoesNotExist:
                e_submissions = None

            # Calculate the final mark for the course.
            has_completed_final = False
            final_percent = 0
            for a_submission in a_submissions:
                percent = (a_submission.assignment.worth / 100)
                percent *= (a_submission.percent / 100)
                final_percent += percent
            for q_submission in q_submissions:
                percent = (q_submission.quiz.worth / 100)
                percent *= (q_submission.percent / 100)
                final_percent += percent
            for e_submission in e_submissions:
                percent = (e_submission.exam.worth / 100)
                percent *= (e_submission.percent / 100)
                final_percent += percent

                if e_submission.exam.is_final:
                    if percent >= 0.50:
                        has_completed_final = True
            final_percent *= 100

            # Validation
            if final_percent < 50:
                response_data = {'status' : 'failure', 'message' : 'you need to pass with at minimum 50%'}
                return HttpResponse(json.dumps(response_data), content_type="application/json")
            if not has_completed_final:
                response_data = {'status' : 'failure', 'message' : 'you need to pass the final exam with at minumum 50%'}
                return HttpResponse(json.dumps(response_data), content_type="application/json")

            # Create or fetch our final mark for this course
            try:
                final_mark = CourseFinalMark.objects.get(
                    course=course,
                    student=student,
                )
                final_mark.percent = final_percent
                final_mark.save()
            except CourseFinalMark.DoesNotExist:
                final_mark = CourseFinalMark.objects.create(
                    course=course,
                    student=student,
                    percent = final_percent,
                )
                final_mark.save()
            response_data = {'status' : 'success', 'message' : 'credit granted'}
        return HttpResponse(json.dumps(response_data), content_type="application/json")


@login_required(login_url='/landpage')
def error_credits_modal(request, course_id, submission_id):
    response_data = {}
    if request.is_ajax():
        if request.method == 'POST':
        
            # Check to see if any fields where missing from the form.
            return render(request, 'course/peer_review/review_modal.html',{
                'user': request.user,
            })

academicstoday_project/student/views/policy.py
from django.shortcuts import render
from django.core import serializers
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.conf import settings
from registrar.models import Course
from registrar.models import Policy
import json
import datetime

# Developer Notes:
# (1) Templates
# https://docs.djangoproject.com/en/1.7/ref/templates
#
# (2) JSON
# https://docs.djangoproject.com/en/1.7/topics/serialization/


@login_required(login_url='/landpage')
def policy_page(request, course_id):
    course = Course.objects.get(id=course_id)
    try:
        policy = Policy.objects.get(course=course)
    except Policy.DoesNotExist:
        policy = None
    return render(request, 'course/policy/view.html',{
        'course' : course,
        'user' : request.user,
        'policy' : policy,
        'tab' : 'policy',
        'HAS_ADVERTISMENT': settings.APPLICATION_HAS_ADVERTISMENT,
        'local_css_urls' : settings.SB_ADMIN_2_CSS_LIBRARY_URLS,
        'local_js_urls' : settings.SB_ADMIN_2_JS_LIBRARY_URLS,
    })

academicstoday_project/student/templates/course/discussion/new_post_modal.html
{% load staticfiles %}
<div class="modal fade" id="new_post_modal" role="dialog">
    <div class="modal-dialog" style="width:750px;">
        <div class="modal-content">
            <div class="modal-header">
                <a href="#" class="btn btn-success pull-right" data-dismiss="modal">×</a>
                <h4>New Post</h4>
            </div>
            <div class="modal-body">
                <form>
                {% for field in form %}
                    <div class="row">
                        <div class="form-group">
                            <div class="fieldWrapper">
                                <label class="col-sm-3 control-label">
                                    {{ field.label }}
                                </label>
                                <div class="col-sm-9">
                                    {{ field }}
                                </div>
                            </div>
                        </div>
                    </div>
                    <br/>
                {% endfor %}
                </form>

                <!-- Error Message Box -->
                <div id="error_box" name="error_box" class="alert alert-danger alert-dismissable" hidden="true">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    ERROR: This is to be filled in by the "print_error" function. If you see this message that means there's an error with your javascript somewhere.
                </div><!-- /.Error Message Box -->
            </div>
            <div class="modal-footer">
                <button onclick="ajax_insert_post({{ thread.thread_id }});"
                             id="submit_post_btn"
                           name="submit_post_btn"
                           type="button"
                          class="btn btn-primary">
                    <i class="fa fa-plus"></i> Submit
                </button>
            </div>
        </div>
    </div>
</div>
<script>
    $(document).ready(function(){
        // When this model hides, we will clear the contents of it.
        $('#new_post_modal').on('hidden.bs.modal', function (e) {
            // Clear all the code inside this modal.
            $('#new_post_modal').html('');
            $('#reply_' + {{ thread.thread_id }} + '_btn').prop("disabled", false); // Unlock button
        })
    });
</script>

academicstoday_project/student/templates/course/discussion/posts_view.html
{% extends 'course/base.html' %}
{% load staticfiles %}
{% block content %}

        <!-- Page Heading -->
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">
                    Discussion
                    <small>Ask any questions here</small>
                </h1>
                <ol class="breadcrumb">
                    <li>
                        <i class="fa fa-university"></i>  <a href="/courses">Courses</a>
                    </li>
                    <li>
                        <i class="fa fa-compass"></i> {{ course.title }}
                    </li>
                    <li>
                        <i class="fa fa-fw fa-comment"></i>  <a href="/course/{{ course.id }}/discussion">Discussion</a>
                    </li>
                    <li class="active">
                        <i class="fa fa-fw fa-comment"></i> Thread #{{ thread.thread_id }}
                    </li>
                </ol>
            </div>
        </div>
        <!-- /.row -->
        
        <!-- Posts Table -->
        <div id="ajax_posts_table"
           name="ajax_posts_table">
            {% include "course/discussion/posts_table.html" %}
        </div>

        <!-- /.row -->
        
<script>
    function ajax_refresh_posts_table()
    {
        $.ajax( {{ thread.thread_id }} + '/posts_table', {
            data: {
               'csrfmiddlewaretoken': '{{ csrf_token }}',
            },
            type: 'post',
            success: function(result) {
               // success code execution here
               $('#ajax_posts_table').html(result); // Update UI.
            },
            error: function(xhr,status,error) {
               // error code here
            },
            complete: function(xhr,status) {
               // completion code here
            }
        });
    }

    function ajax_new_post_modal(thread_id)
    {
        $('#reply_' + thread_id + '_btn').prop("disabled", true); // Lock button
        $.ajax( thread_id + '/new_post', {
            data: {
               'csrfmiddlewaretoken': '{{ csrf_token }}',
            },
            type: 'post',
            success: function(result) {
               // success code execution here
               $('#ajax_new_post').html(result); // Update UI.
               $('#new_post_modal').modal();     // Unhide view.
            },
            error: function(xhr,status,error) {
               // error code here
            },
            complete: function(xhr,status) {
               // completion code here
            }
        });
    }

    function ajax_insert_post(thread_id)
    {
        $('#submit_post_btn').prop("disabled", true);
        if (typeof(thread_id)==='undefined')
        {
            thread_id = 0;
        }
    
        // Create a FormData Object using your form dom element and load
        // up the initial data first, then update it on question type.
    
        // Basic
        var data = new FormData();
        data.append('csrfmiddlewaretoken', '{{ csrf_token }}');
        data.append('title', $('#id_title').val());
        data.append('text', $('#id_text').val());
        data.append('thread_id', thread_id);
    
        jQuery.ajax({
            url: thread_id + '/insert_post',
            data: data,
            cache: false,
            contentType: false,
            processData: false,
            type: 'POST',
            success: function(json_result){
                // success code execution here
                if (json_result.status == 'success')
                {
                    $('#new_post_modal').modal('hide');
                    ajax_refresh_posts_table();
                }
                else
                {
                    alert(json_result.message);
                }
            },
            error: function(xhr,status,error) {
                // error code here
            },
            complete: function(xhr,status) {
                // completion code here
                $('#submit_post_btn').prop("disabled", false);
            }
        });
    }

    function ajax_delete_thread(thread_id)
    {
        var url = 'delete_thread';
    
        $.ajax( url, {
            data: {
               'csrfmiddlewaretoken': '{{ csrf_token }}',
               'thread_id': thread_id,
            },
            type: 'post',
            success: function(result) {
               // success code execution here
               if (result.status == 'success')
               {
                    ajax_refresh_posts_table(); // Reload UI.
               }
               else
               {
                    print_error(result.message);
               }
            },
            error: function(xhr,status,error) {
               // error code here
            },
            complete: function(xhr,status) {
               // completion code here
            }
        });
    }

    function ajax_view_thread(thread_id)
    {
        window.location = 'thread/' + thread_id;
    }

    /**
     * Prints a error box with the contents of the errors received from the server.
     */
    function print_error(json_result)
    {
        $('#error_box').prop("hidden", false); // Display error box.
    
        // Iterate through the JSON array of arrays and generate an error string.
        var message = "<b>Error(s):</b><hr/>";
        var data = $.parseJSON(json_result)
        for (var key in data) {
            if (data.hasOwnProperty(key)) { // this will check if key is owned by data object and not by any of it's ancestors
                message += "<p>" + key + ": " + data[key] + "<p>";
            }
        }
        
        // Replace the error string with the contents of the error box.
        $('#error_box').html(message);
    }
</script>

<!-- Modal -->
<div id="ajax_new_post"
   name="ajax_new_post"></div>
<!-- /.Modal -->

{% endblock content %}

academicstoday_project/student/templates/course/discussion/threads_view.html
{% extends 'course/base.html' %}
{% load staticfiles %}
{% block content %}

        <!-- Page Heading -->
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">
                    Discussion
                    <small>Ask any questions here</small>
                </h1>
                <ol class="breadcrumb">
                    <li>
                        <i class="fa fa-university"></i>  <a href="/courses">Courses</a>
                    </li>
                    <li>
                        <i class="fa fa-compass"></i> {{ course.title }}
                    </li>
                    <li class="active">
                        <i class="fa fa-fw fa-comment"></i> Discussion
                    </li>
                </ol>
            </div>
        </div>
        <!-- /.row -->
        
        <!-- Discussion Forum -->
        <div id="ajax_threads_table"
           name="ajax_threads_table">
            {% include "course/discussion/threads_table.html" %}
        </div>
        <!-- /.row -->
        
<script>
    function ajax_refresh_threads_table()
    {
        $.ajax( 'threads_table', {
               data: {
                    'csrfmiddlewaretoken': '{{ csrf_token }}',
               },
               type: 'post',
               success: function(result) {
                    // success code execution here
                    $('#ajax_threads_table').html(result); // Update UI.
               },
               error: function(xhr,status,error) {
                    // error code here
               },
               complete: function(xhr,status) {
                    // completion code here
            }
        });
    }
    
    function ajax_new_thread_modal(course_id)
    {
        $('#new_thread_btn').prop("disabled", true); // Lock button
        $.ajax( 'new_thread', {
            data: {
               'csrfmiddlewaretoken': '{{ csrf_token }}',
               'course_id': course_id,
            },
            type: 'post',
            success: function(result) {
               // success code execution here
               $('#ajax_new_thread').html(result); // Update UI.
               $('#new_thread_modal').modal();     // Unhide view.
            },
            error: function(xhr,status,error) {
               // error code here
            },
            complete: function(xhr,status) {
               // completion code here
            }
        });
    }

    function ajax_insert_thread(course_id)
    {
        $('#submit_thread_btn').prop("disabled", true);
        if (typeof(course_id)==='undefined')
        {
            course_id = 0;
        }
    
        // Create a FormData Object using your form dom element and load
        // up the initial data first, then update it on question type.
    
        // Basic
        var data = new FormData();
        data.append('csrfmiddlewaretoken', '{{ csrf_token }}');
        data.append('title', $('#id_title').val());
        data.append('text', $('#id_text').val());
        data.append('course_id', course_id);
    
        jQuery.ajax({
            url: 'insert_thread',
            data: data,
            cache: false,
            contentType: false,
            processData: false,
            type: 'POST',
            success: function(json_result){
                // success code execution here
                if (json_result.status == 'success')
                {
                    $('#new_thread_modal').modal('hide');
                    ajax_refresh_threads_table();
                }
                else
                {
                    alert(json_result.message);
                }
            },
            error: function(xhr,status,error) {
                // error code here
            },
            complete: function(xhr,status) {
                // completion code here
                $('#submit_thread_btn').prop("disabled", false);
            }
        });
    }

    function ajax_delete_thread(thread_id)
    {
        $('#del_' + thread_id + '_btn').prop("disabled", true); // Lock button
        $.ajax( 'delete_thread', {
            data: {
               'csrfmiddlewaretoken': '{{ csrf_token }}',
               'thread_id': thread_id,
            },
            type: 'post',
            success: function(result) {
               // success code execution here
               if (result.status == 'success')
               {
                    ajax_refresh_threads_table(); // Reload UI.
               }
               else
               {
                    print_error(result.message);
               }
            },
            error: function(xhr,status,error) {
               // error code here
            },
            complete: function(xhr,status) {
               // completion code here
               $('#del_' + thread_id + '_btn').prop("disabled", false); // Unlock button
            }
        });
    }

    function ajax_view_thread(thread_id)
    {
        window.location = 'thread/' + thread_id;
    }

    /**
     * Prints a error box with the contents of the errors received from the server.
     */
    function print_error(json_result)
    {
        $('#error_box').prop("hidden", false); // Display error box.
    
        // Iterate through the JSON array of arrays and generate an error string.
        var message = "<b>Error(s):</b><hr/>";
        var data = $.parseJSON(json_result)
        for (var key in data) {
            if (data.hasOwnProperty(key)) { // this will check if key is owned by data object and not by any of it's ancestors
                message += "<p>" + key + ": " + data[key] + "<p>";
            }
        }
    
        // Replace the error string with the contents of the error box.
        $('#error_box').html(message);
    }
</script>

<!-- Modal -->
<div id="ajax_new_thread"
   name="ajax_new_thread"></div>
<!-- /.Modal -->

{% endblock content %}